spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qwest
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  mail:
    host: localhost
    port: 1025

  security:
    remember-me-key: secret

avatars:
  api-url: http://localhost:3000/9.x/{style}/svg?seed={username}
  default-style: adventurer-neutral
