@startuml
set separator none
title Shared

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("QwestApplication.QwestApplication_boundary", "QwestApplication", $tags="") {
  Component(QwestApplication.QwestApplication.Shared, "Shared", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml